DOCKER_ARDUINO-CLI_INSTALL_IMAGE=ardiono-cli-install
VERSION=0.0.2

create-arduino-cli-install-docker-image:
	docker build -f "itsAmeeDockerio.dockerfile" -t $(DOCKER_ARDUINO-CLI_INSTALL_IMAGE):$(VERSION) "."


